# Generated by Django 6.0.7 on 2026-07-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('pontos', models.IntegerField()),
                ('tempo', models.IntegerField()),
                ('movimentos', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
